parameters:
    assetpicker.console_listener.class:  Netresearch\AssetPickerBundle\Listener\ConsoleListener
    assetpicker.kernel_listener.class:  Netresearch\AssetPickerBundle\Listener\KernelListener
    assetpicker.twig.class:              Netresearch\AssetPickerBundle\Twig\AssetPickerExtension

services:
    assetpicker.console_listener:
        class: '%assetpicker.console_listener.class%'
        tags:
            - { name: kernel.event_listener, event: console.terminate, method: onCommandTerminate }

    assetpicker.kernel_listener:
        class: '%assetpicker.kernel_listener.class%'
        arguments:
            - '@router'
            - '@kernel'
            - '@oro_config.global'
            - '@pim_notification.manager.notification'
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }


    assetpicker.twig_extension:
        class: '%assetpicker.twig.class%'
        arguments:
            - '@service_container'
            - '@router'
        tags:
            - { name: twig.extension }
